
# Site settings
title: Nilsonlinux
email:
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://nilsonsoft.github.io" # the base hostname & protocol for your site

# User setting
owner:
email:
facebook_username: nilsonlinux
twitter_username: nilsonlinux
github_username: nilsonlinux
address:
  - line:
  - line:
  # Feel free to add more lines here 
telephone:
copyright:

# API settings
google_api_key:

# Build settings
gems: [jekyll-paginate]

markdown: kramdown
# toc_levels: 1..2
